### ISSUE TITLE
The data contained in 360SD-Net/data are not suit.

### ISSUE THREAD

**Issue by minygd** [albert100121/360SD-Net#1]
Hello, I download your sample images from **MP3D** and **SF3D** provided in this repository. But I found that the up-view and down-view pictures are almost the same in your folders.  So there are no differences between them.
The same thing occur in realworld folder, too. Please check out in your convenience, and let me know if I am wrong.

Best.

**Comment by albert100121** [comment]
Hello, I've check through the data in the folder, and they seem OK.
As you've mentioned, the scenes in the top and bottom folder are similar, since they are stereo views with 20 cm of camera baseline.
In order to see the difference by human perception, please put them side by side and focus on the near objects, thank you.

Best regards.

**Comment by albert100121** [comment]
> Hello, I download your sample images from **MP3D** and **SF3D** provided in this repository. But I found that the up-view and down-view pictures are almost the same in your folders. So there are no differences between them.
> The same thing occur in realworld folder, too. Please check out in your convenience, and let me know if I am wrong.
> 
> Best.

Hello, I've check through the data in the folder, and they seem OK.
As you've mentioned, the scenes in the top and bottom folder are similar, since they are stereo views with 20 cm of camera baseline.
In order to see the difference by human perception, please put them side by side and focus on the near objects, thank you.

Best regards.

**Comment by albert100121** [comment]
> Hello, I download your sample images from **MP3D** and **SF3D** provided in this repository. But I found that the up-view and down-view pictures are almost the same in your folders. So there are no differences between them.
> The same thing occur in realworld folder, too. Please check out in your convenience, and let me know if I am wrong.
> 
> Best.

Hello, I've checked through the data in the folder, and they seem OK.
As you've mentioned, the scenes in the top and bottom folder are similar, since they are stereo views with 20 cm of camera baseline.
In order to see the difference by human perception, please put them side by side and focus on the near objects, thank you.

Best regards.

**Comment by minygd** [comment]
Thanks for your reply. Since the baseline is small, the difference is small too. I could see it now as you suggested.

The issue will be closed.
